# Generated by Django 5.2.6 on 2025-11-20 19:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Offre',
            fields=[
                ('IDOffre', models.AutoField(primary_key=True, serialize=False)),
                ('entrepriseOffre', models.CharField(max_length=200)),
                ('nomContactOffre', models.CharField(max_length=100)),
                ('prenomContactOffre', models.CharField(blank=True, max_length=100, null=True)),
                ('emailContactOffre', models.EmailField(max_length=254)),
                ('dateDepotOffre', models.DateTimeField(auto_now_add=True)),
                ('titreOffre', models.CharField(max_length=200)),
                ('detailsOffre', models.TextField()),
                ('statutOffre', models.CharField(choices=[('attente', 'En attente de validation'), ('validee', 'Validée'), ('refusee', 'Refusée'), ('cloturee', 'Clôturée')], default='attente', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Candidature',
            fields=[
                ('IDCandidature', models.AutoField(primary_key=True, serialize=False)),
                ('dateCandidature', models.DateTimeField(auto_now_add=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('offre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appstage.offre')),
            ],
            options={
                'unique_together': {('offre', 'etudiant')},
            },
        ),
    ]
