# Generated by Django 5.2.7 on 2025-12-03 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appstage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offre',
            name='imageOffre',
            field=models.ImageField(blank=True, null=True, upload_to='offres_images/'),
        ),
    ]
