# Generated by Django 5.2.7 on 2025-12-07 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appstage', '0002_offre_imageoffre'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidature',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='cvs/'),
        ),
        migrations.AddField(
            model_name='candidature',
            name='lettre',
            field=models.FileField(blank=True, null=True, upload_to='lettres/'),
        ),
        migrations.AddField(
            model_name='candidature',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
